[build]
  publish = "src"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200
  
# Additional redirect to allow access to blog content
[[redirects]]
  from = "/.netlify/functions/post/*"
  to = "/.netlify/functions/post/:splat"
  status = 200
