[build]
  publish = "src"
  functions = "functions"

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[functions]
  included_files = [
    "src/content/**/index.md",
    "src/content/**/*.png",
    "src/content/**/*.jpg",
    "src/content/**/*.jpeg",
    "src/content/**/*.gif",
    "src/content/**/*.webp",
    "src/content/**/*.svg",
    "data/reactions/*.json"
  ]

# Include all files in deployment
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

[[headers]]
  for = "/content/*"
  [headers.values]
    Content-Type = "text/plain"

